name: Terraform Plan Comment
description: Post the output of `terraform plan` to a pull request comment.
author: Oliver Borchert
branding:
  icon: git-pull-request
  color: purple
inputs:
  token:
    description: The token to use for authenticating against the GitHub API.
    required: true
  planfile:
    description: The path to the planfile whose changes to post.
    required: true
  terraform-cmd:
    description: The command to execute for calling the Terraform binary.
    required: true
    default: terraform
  working-directory:
    description: The directory where the Terraform binary should be called.
    required: true
    default: "."
  header:
    description: The header to use for the pull request comment.
    required: true
    default: 📝 Terraform Plan
  skip-empty:
    description: Whether to skip posting a pull request comment when no changes need to be performed.
    required: true
    default: "false"
runs:
  using: node20
  main: dist/index.js
