name: Terrafom Plan
on: pull_request

env:
  TG_NON_INTERACTIVE: "true"
  TG_NO_COLOR: "true"
  TG_ALL: "true"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Initialize
        working-directory: tests/fixtures/basic/7-create-hundreds
        run: |
          terraform init
          terraform plan -out .planfile
      - name: Post PR comment
        uses: ./
        with:
          token: ${{ github.token }}
          working-directory: tests/fixtures/basic/7-create-hundreds
          planfile: .planfile
